sudo: false
language: node_js
cache:
  directories:
    - node_modules
node_js:
  - "stable"
  - "6.0.0"
  - "5.11.0"
  - "4.4.3"
  - "0.12.13"
script:
  - npm run test:single
  - npm run check-coverage
after_success:
  - npm run report-coverage
