sudo: false
language: node_js
cache:
  directories:
    - node_modules
node_js:
  - "stable"
  - "5.7"
  - "4.3.1"
  - "0.12"
script:
  - npm run test:single
  - npm run check-coverage
after_success:
  - npm run report-coverage
